version: '3'

services:
  database:
    build:
      context: postgres/.
    restart: always
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${DATABASE_USER:-postgres}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD:-password}"
      DATABASE_NAME: "${DATABASE_NAME:-banking}"
      DATABASE_TYPE: "${DATABASE_TYPE:-postgres}"

  app:
    build:
      context: .
    ports:
        - "${APP_PORT:-8080}:8080"
    links:
      - "database:database.localhost"
    environment:
      DATABASE_HOST: "${DATABASE_HOST:-database.localhost}"
      DATABASE_NAME: "${DATABASE_NAME:-banking}"
      DATABASE_USER: "${DATABASE_USER:-postgres}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD:-password}"
      DATABASE_TYPE: "${DATABASE_TYPE:-postgresql}"