version: '3'

services:
  database:
    build:
      context: postgres/.
    restart: always
    ports:
      - ${DATABASE_PORT:-5432}:${DATABASE_PORT:-5432}
    environment:
      POSTGRES_USER: "${DATABASE_USER:-postgres}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD:-password}"
      DATABASE_NAME: "${DATABASE_NAME:-banking}"
      DATABASE_TYPE: "${DATABASE_TYPE:-postgres}"

  app:
    build:
      context: .
    ports:
        - 8080:8080
    links:
      - "database:database.localhost"
    environment:
      DATABASE_CONNECTION_URL: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME:-banking}"
      DATABASE_USER: "${DATABASE_USER:-postgres}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD:-password}"